inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.2  
  Exclude:
    - ./db/**/*
    - ./bin/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/**/*
  DefaultFormatter: progress

Layout/IndentationWidth:
  Enabled: true
  Width: 2  # or any preferred width

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  # Indentation for method calls should be aligned to the first argument.

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses
  # Prefer omitting parentheses for methods without arguments.

# Enable checks for unnecessary spaces
Layout/EmptyLineAfterGuardClause:
  Enabled: true
  # Ensures that there's an empty line after guard clauses.
  
# Allow empty lines to separate sections of methods
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  # Ensure a consistent blank line around block bodies.

# Enforce consistent indentation for multiline blocks
Layout/SpaceAroundOperators:
  Enabled: true
  # Ensure consistent spaces around operators.

# Enforce consistent spacing after commas
Layout/SpaceAfterComma:
  Enabled: true
  # Commas in method calls, hashes, etc., should be followed by a single space.

# Enforce consistent spacing in array, hash, and method arguments
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  # No space inside array brackets.

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
  # No space inside hash literal braces.

# Enable consistent naming conventions
Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case

# Check for unnecessary returns
Style/RedundantReturn:
  Enabled: true
  # Detect redundant `return` in methods.

# Ensure all class and module names are CamelCase
Naming/ClassAndModuleCamelCase:
  Enabled: true
  # Class and module names should be in CamelCase.

# Avoid long lines of code
Layout/LineLength:
  Enabled: true
  Max: 120
  # Max line length should be 120 characters to ensure readability.

# Require consistent use of snake_case for variable names
Naming/VariableName:
  Enabled: true
  EnforcedStyle: snake_case
  # Variables and method arguments should be in snake_case.

# Enforce consistent whitespace around parentheses in method calls
Layout/SpaceInsideParens:
  Enabled: true
  EnforcedStyle: no_space
  # No spaces inside parentheses.

# Enforce consistency in `if`/`else` expressions
Style/IfUnlessModifier:
  Enabled: true
  # Avoid using `if` and `unless` modifiers for clarity.

# Additional custom rules
Metrics/MethodLength:
  Max: 20 # Max 20 lines per method
  # Keep methods small and readable.

Metrics/BlockLength:
  Max: 25 # Max 25 lines per block
  # Keep blocks small and concise.

Rails/ApplicationRecord:
  Enabled: true
